# Generated by Django 4.2.13 on 2024-06-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'role')},
        ),
    ]
