# Generated by Django 4.2.13 on 2024-06-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author_created_at_author_created_by_book_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
    ]
